server:
  port: 8081

spring:
  application:
    name: backend-service

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes

server:
  port: 8080
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
