server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: route1
          uri: http://localhost:8081
          predicates:
            - Path=/backend/**
          filters:
            - StripPrefix=1
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE