server:
  port: 8080

spring:
  application:
    name: frontend-service

gateway:
  url: http://localhost:9090

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes

server:
  port: 8080
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

gateway:
  url: http://example-gateway

